// <auto-generated />
namespace Web_DrugStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddGiaCuToSanPham : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGiaCuToSanPham));
        
        string IMigrationMetadata.Id
        {
            get { return "202411152222404_AddGiaCuToSanPham"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
